FROM docker.elastic.co/elasticsearch/elasticsearch:6.1.3
#RUN bin/elasticsearch-plugin install repository-s3 --batch
RUN bin/elasticsearch-plugin install  -v https://raw.githubusercontent.com/gianrubio/elasticsearch/hosted-jar/hosted-jar/repository-s3-6.1.3-SNAPSHOT.zip

